spring.application.name=jpalibrary
spring.jpa.show-sql=true

server.port=9000

logging.level.root=ERROR
logging.level.co.simplon=INFO
logging.level.org.springframework.boot.autoconfigure.h2=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

spring.datasource.url=jdbc:h2:mem:mydb
spring.h2.console.enabled=true
spring.h2.console.path=/h2
